/*
 * Custom, self-measuring ShadowNode for <AdvancedTextView>.
 *
 * This file intentionally *shadows* the file generated by react-native-codegen
 * at:
 *   build/generated/source/codegen/jni/react/renderer/components/AdvancedTextViewSpec/ShadowNodes.h   (Android)
 *   <codegen>/react/renderer/components/AdvancedTextViewSpec/ShadowNodes.h                             (iOS)
 *
 * The generated version defines `AdvancedTextViewShadowNode` as a plain
 * `ConcreteViewShadowNode` alias, which has no Yoga measure function. That is
 * why <AdvancedText> renders nothing unless an explicit `height` is provided.
 *
 * This version replaces the alias with a real class that opts into Yoga
 * measurement (`LeafYogaNode | MeasurableYogaNode`) and implements
 * `measureContent()` using React Native's own `TextLayoutManager` -- the exact
 * engine <Text> uses -- so the component derives its height from its text and
 * the available width, just like <Text>.
 *
 * The generated `ComponentDescriptors.h` (`using AdvancedTextViewComponentDescriptor
 * = ConcreteComponentDescriptor<AdvancedTextViewShadowNode>`) therefore wraps
 * this class automatically; no other wiring change is required on either
 * platform. The `AdvancedTextViewComponentName` symbol is still defined by the
 * generated `ShadowNodes.cpp`.
 *
 * For this shadowing to take effect, `common/cpp` must appear on the include
 * path *before* the codegen output directory:
 *   - Android: handled by `android/CMakeLists.txt` (see `target_include_directories`)
 *   - iOS:     handled by `AdvancedText.podspec` (HEADER_SEARCH_PATHS)
 */

#pragma once

#include <memory>

#include <jsi/jsi.h>
#include <react/renderer/attributedstring/AttributedString.h>
#include <react/renderer/components/AdvancedTextViewSpec/EventEmitters.h>
#include <react/renderer/components/AdvancedTextViewSpec/Props.h>
#include <react/renderer/components/AdvancedTextViewSpec/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/core/LayoutConstraints.h>
#include <react/renderer/core/LayoutContext.h>
#include <react/renderer/core/ShadowNode.h>
#include <react/renderer/core/ShadowNodeFragment.h>

namespace facebook::react {

class TextLayoutManager;

// Defined by the codegen-generated ShadowNodes.cpp.
JSI_EXPORT extern const char AdvancedTextViewComponentName[];

/*
 * `ShadowNode` for <AdvancedTextView> component.
 */
class AdvancedTextViewShadowNode final : public ConcreteViewShadowNode<
                                            AdvancedTextViewComponentName,
                                            AdvancedTextViewProps,
                                            AdvancedTextViewEventEmitter,
                                            AdvancedTextViewState> {
 public:
  // "create" constructor: (fragment, family, traits)
  using ConcreteViewShadowNode::ConcreteViewShadowNode;

  // "clone" constructor: carry the resolved TextLayoutManager across clones.
  AdvancedTextViewShadowNode(
      const ShadowNode& sourceShadowNode,
      const ShadowNodeFragment& fragment);

  static ShadowNodeTraits BaseTraits() {
    auto traits = ConcreteViewShadowNode::BaseTraits();
    // Opt into Yoga measurement. `MeasurableYogaNode` requires `LeafYogaNode`.
    traits.set(ShadowNodeTraits::Trait::LeafYogaNode);
    traits.set(ShadowNodeTraits::Trait::MeasurableYogaNode);
    return traits;
  }

#pragma mark - LayoutableShadowNode

  Size measureContent(
      const LayoutContext& layoutContext,
      const LayoutConstraints& layoutConstraints) const override;

 private:
  /*
   * Builds a single-fragment `AttributedString` from the component props
   * (text + font attributes), mirroring how the native views render it.
   */
  AttributedString getAttributedString() const;

  // Lazily created on first measure, then reused / copied across clones.
  mutable std::shared_ptr<const TextLayoutManager> textLayoutManager_;
};

} // namespace facebook::react
